### ISSUE TITLE
ivy-sso-openid-connect: The Jboss/keycloak has been removed

### ISSUE THREAD

**Issue by mao-aavn** [axonivy/docker-samples#153]
Hi there, 

I got this error while trying to start the the /docker-samples/ivy-sso-openid-connect image.
I had a quick check on the Docker repo and it's not existing anymore. Can you pls check ?
![image](https://github.com/axonivy/docker-samples/assets/136697041/ac456be7-b06b-4c81-b1fa-5de790e76ca6)

Thanks and br,
Mao.

**Comment by alexsuter** [comment]
Will be fixed here: 
https://github.com/axonivy/docker-samples/pull/154
